SET NAMES 'UTF8';

CREATE DATABASE movie_time CHARACTER SET UTF8 COLLATE utf8_unicode_ci;

USE movie_time;

CREATE TABLE THEATER(THEATER_ID VARCHAR(50), 
			SOURCE_ID VARCHAR(255),
			NAME VARCHAR(255),
			ADDRESS VARCHAR(255), 
			PHONE VARCHAR(255),
			GPS VARCHAR(255),
			PART_AREA VARCHAR(100),
			AREA VARCHAR(200),
			TIME_STAMP VARCHAR(200),
			PRIMARY KEY (THEATER_ID));


CREATE TABLE THEATER_TIME(THEATER_ID VARCHAR(50) NOT NULL,
			HALL_NAME VARCHAR(255),
			MOVIE_NAME VARCHAR(255),
			TIME VARCHAR(255),
			FOREIGN KEY(THEATER_ID) REFERENCES THEATER(THEATER_ID));

CREATE TABLE AREAS(AREA_NAME VARCHAR(255));

